import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

INVENTORY_HEIGHT = (SCREEN_HEIGHT/100) * 15 # 15% of the screen height
FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
PURPLE = (160, 32, 240)
SPEECH_SIZE = 25
SPEECH_FONT = 'freesansbold.ttf'

BACKGROUND_VOLUME = 0.3


def at_percentage_width(percentage):
    print((SCREEN_WIDTH/100)*percentage)
    return (SCREEN_WIDTH/100)*percentage

def at_percentage_height(percentage):
    print(((SCREEN_HEIGHT-INVENTORY_HEIGHT)/100)*percentage)
    return ((SCREEN_HEIGHT-INVENTORY_HEIGHT)/100)*percentage

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_LIVES = 3

SHIP_SPAWN_RATE = 2  # seconds
SHIP_MAX_RADIUS = 20
SHIP_MIN_RADIUS = 10


AMMO_SPAWN_RATE = 5  # seconds